# Generated by Django 5.1 on 2024-08-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentquiz',
            name='num_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentquiz',
            name='num_incorrect',
            field=models.IntegerField(default=0),
        ),
    ]
