# Generated by Django 5.1 on 2024-08-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquiz',
            name='time_taken',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
